In [1]:
import pandas as pd
import utils
import plotly.graph_objects as go

In [2]:
pair = "EUR_USD"
granularity = "H1"

In [3]:
df = pd.read_pickle(utils.get_data_filename_ipynb(pair, granularity))

In [4]:
df.describe()

             volume
count   3999.000000
mean    3053.000500
std     2238.146639
min       95.000000
25%     1551.000000
50%     2543.000000
75%     3905.000000
max    21907.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3999 entries, 0 to 3998
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    3999 non-null   object
 1   volume  3999 non-null   int64
 2   mid_o   3999 non-null   object
 3   mid_h   3999 non-null   object
 4   mid_l   3999 non-null   object
 5   mid_c   3999 non-null   object
 6   bid_o   3999 non-null   object
 7   bid_h   3999 non-null   object
 8   bid_l   3999 non-null   object
 9   bid_c   3999 non-null   object
 10  ask_o   3999 non-null   object
 11  ask_h   3999 non-null   object
 12  ask_l   3999 non-null   object
 13  ask_c   3999 non-null   object
dtypes: int64(1), object(13)
memory usage: 437.5+ KB

In [6]:
non_cols = ['time', 'volume']

In [7]:
mod_cols = [x for x in df.columns if x not in non_cols]

In [8]:
mod_cols

['mid_o',
 'mid_h',
 'mid_l',
 'mid_c',
 'bid_o',
 'bid_h',
 'bid_l',
 'bid_c',
 'ask_o',
 'ask_h',
 'ask_l',
 'ask_c']

In [9]:
df[mod_cols] = df[mod_cols].apply(pd.to_numeric)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3999 entries, 0 to 3998
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    3999 non-null   object
 1   volume  3999 non-null   int64
 2   mid_o   3999 non-null   float64
 3   mid_h   3999 non-null   float64
 4   mid_l   3999 non-null   float64
 5   mid_c   3999 non-null   float64
 6   bid_o   3999 non-null   float64
 7   bid_h   3999 non-null   float64
 8   bid_l   3999 non-null   float64
 9   bid_c   3999 non-null   float64
 10  ask_o   3999 non-null   float64
 11  ask_h   3999 non-null   float64
 12  ask_l   3999 non-null   float64
 13  ask_c   3999 non-null   float64
dtypes: float64(12), int64(1), object(1)
memory usage: 437.5+ KB

In [12]:
df.describe()

,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
count,3999.000000,3999.000000,3999.000000,3999.000000,3999.000000,3999.000000,3999.000000,3999.000000,3999.000000,3999.000000,3999.000000,3999.000000,3999.000000
mean,3053.000500,1.082755,1.083254,1.082254,1.082756,1.082671,1.083176,1.082171,1.082677,1.082838,1.083336,1.082333,1.082835
std,2238.146639,0.009087,0.009097,0.009064,0.009087,0.009086,0.009095,0.009063,0.009086,0.009088,0.009098,0.009066,0.009088
min,95.000000,1.061000,1.061260,1.060110,1.061010,1.060920,1.061190,1.060040,1.060940,1.061070,1.061330,1.060180,1.061080
25%,1551.000000,1.076470,1.076910,1.076040,1.076480,1.076385,1.076840,1.075960,1.076405,1.076550,1.076980,1.076110,1.076560
50%,2543.000000,1.083160,1.083690,1.082660,1.083200,1.083090,1.083620,1.082580,1.083120,1.083240,1.083760,1.082740,1.083270
75%,3905.000000,1.088445,1.088865,1.087930,1.088425,1.088345,1.088785,1.087850,1.088340,1.088530,1.088955,1.088005,1.088500
max,21907.000000,1.112920,1.113960,1.112270,1.112940,1.112840,1.113880,1.112190,1.112860,1.112990,1.114040,1.112350,1.113020

In [13]:
df_plot = df.iloc[-100:].copy()

In [14]:
df_plot.shape

(100, 14)

In [17]:
fig = go.Figure()
fig.add_trace(go.Candlestick(
    x=df_plot.time, open=df_plot.mid_o, high=df_plot.mid_h, low=df_plot.mid_l, close=df_plot.mid_c
))
fig.show()

TypeError: 'module' object is not callable